<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Styles\Fonts\NeoSansStd-Medium.otf" />
    <None Remove="Styles\Fonts\NeoSansStd-Regular.otf" />
    <None Remove="Styles\Icons\icalculate_high_resolution_logo_48x48.ico" />
    <None Remove="Styles\Images\iCalculateLogo-no-background_220x49.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="Prism.Core" Version="8.1.97" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Styles\Fonts\NeoSansStd-Medium.otf" />
    <Resource Include="Styles\Fonts\NeoSansStd-Regular.otf" />
    <Resource Include="Styles\Icons\icalculate_high_resolution_logo_48x48.ico" />
    <Resource Include="Styles\Images\iCalculateLogo-no-background_220x49.png" />
  </ItemGroup>

</Project>
